plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.10'
	id 'io.spring.dependency-management' version '1.1.6'
    id 'org.jetbrains.kotlin.jvm'
}

group = 'com.project'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Spring Boot 기본 의존성
	implementation 'org.springframework.boot:spring-boot-starter-web' // 웹 애플리케이션 및 REST API 개발
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // JPA와 데이터베이스 연동
	implementation 'org.springframework.boot:spring-boot-starter-security' // Spring Security 지원
	implementation 'org.springframework.boot:spring-boot-starter-graphql'

	// MySQL 데이터베이스 드라이버
	runtimeOnly 'com.mysql:mysql-connector-j'

	// Mapstruct
	implementation 'org.mapstruct:mapstruct:1.6.3'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

	// Lombok
	compileOnly 'org.projectlombok:lombok' // 컴파일 시 Lombok 지원
	annotationProcessor 'org.projectlombok:lombok' // Lombok 어노테이션 처리
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

	// swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0' // API 자동 문서화를 위한 swagger

	// Querydsl
	implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
	annotationProcessor 'com.querydsl:querydsl-apt:5.0.0:jakarta'
	annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
	annotationProcessor 'jakarta.persistence:jakarta.persistence-api'

	// swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0' // API 자동 문서화를 위한 swagger

	// Querydsl
	implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
	annotationProcessor 'com.querydsl:querydsl-apt:5.0.0:jakarta'
	annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
	annotationProcessor 'jakarta.persistence:jakarta.persistence-api'

	// 테스트 의존성
	testImplementation 'org.springframework.boot:spring-boot-starter-test' // Spring Boot 테스트
	testImplementation 'org.springframework.security:spring-security-test' // Spring Security 테스트
	testImplementation 'org.springframework.graphql:spring-graphql-test' // Graphql 테스트
	testImplementation 'com.h2database:h2' // 테스트용 H2 데이터베이스
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher' // JUnit 테스트 실행기
	testAnnotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8" // mapstruct 테스트
}

tasks.named('test') {
	useJUnitPlatform()
}


